spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///integration-tests-db
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:db.schema/schema.sql
  liquibase:
    enabled: false
jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
