server:
  port: 8082
spring:
  config:
    activate:
      on-profile: local
  application:
    name: report-service
  scheduler:
    cron: 0 0 20 * * *
  kafka:
    consumer:
      group-id: report-service
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
rest-api-service:
  auth:
    jwt-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiLmJyaXR2YUBleGFtcGxlLmNvbSIsImV4cCI6MTc0NzA3NTM1MiwiaWF0IjoxNzQ2OTg4OTUyLCJhdXRob3JpdGllcyI6bnVsbH0.pDYsA9NIKq7a5M29sSoB98YWBCXsu82O9FO0c1wBANM
