server:
  port: 8082
spring:
  config:
    activate:
      on-profile: local
  application:
    name: report-service
  scheduler:
    cron: 0 0 20 * * *
  kafka:
    consumer:
      group-id: report-service
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
